name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Build images
        timeout-minutes: 10
        run: docker compose build

      - name: Setup Postgres DB
        run: |
          docker compose up -d postgres
          docker compose logs postgres
          sleep 5
          cd postgres
          psql "user=postgres hostaddr=127.0.0.1 port=5432 password=postgres" < scripts/db-v2.sql

      - name: Run containers
        timeout-minutes: 10
        run: |
          docker compose up -d reservation_service
          docker compose up -d payment_service
          docker compose up -d loyalty_service
          docker compose up -d queue_service
          docker compose up -d gateway_service

          docker compose logs reservation_service
          docker compose logs payment_service
          docker compose logs loyalty_service
          docker compose logs queue_service
          docker compose logs gateway_service
          
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050

      - name: Python3 Setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Requirements
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          cd hotels_booking_system/services/gateway_service/unit_tests
          pytest .

      - name: Wait 5s
        uses: jakejarvis/wait-action@master
        with:
          time: '5s'

      - name: Run API Tests
        timeout-minutes: 5
        run: ./scripts/test-script.sh
        env:
          VARIANT: v2
          SERVICE_NAME: loyalty_service
          PORT_NUMBER: 8050

#      - uses: education/autograding@v1
#        id: autograder
#        continue-on-error: true

#      - name: Github auto grader mark
#        uses: Romanow/google-sheet-autograder-marker@v1.0
#        with:
#          google_token: ${{secrets.GOOGLE_API_KEY}}
#          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
#          homework_number: 3
#          user_column: 'D'
#          column_offset: 'F'
#          mark: "'+"

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v